### ISSUE TITLE
Figure out how to send Ether to a payable function via Javascript

### ISSUE THREAD

**Issue by tikimeat** [strange-labs-uk/ethereum-lottery#12]
We need to implement the buy button but, unfortunately, every time we try to send Ether via metamask to a payable function we get the following error:

`Error: VM Exception while processing transaction: revert`

**Comment by brtknr** [comment]
This now works but the first transaction has to be send via truffle, I can't figure out why...

So
```
truffle (develop)> deploy --reset // copy the Lottery contract address across to lottery.js
truffle (develop)> Lottery.deployed().then(i=>i.sendVal({value:10}))
```

Only now you can send Wei to the contract in the front end. God knows why...

**Comment by tikimeat** [comment]
Oh that's strange, sendVal always seems to work for me even without calling it through the console first. For some reason buyTokens always fails when I call it in the same way though.

**Comment by brtknr** [comment]
Managed to get it working using MetaMask! All good now :) think we can close this issue as far as I can tell.

**Comment by nuxibyte** [comment]
yep.
