### ISSUE TITLE
Work out how to interact with contract from truffle

### ISSUE THREAD

**Issue by binocarlos** [strange-labs-uk/ethereum-lottery#2]
From the Readme:

In the truffle(develop)> console:

```
deploy --reset
test
```

Now you can interact with the lottery contract, you can create a pointer to it as follows:

```
var lot = Lottery.at(Lottery.address)
```

However, I have not figure out how to interact with it beyond this yet so if anyone can figure it out, please share your wisdom.

**Comment by ccdle12** [comment]
I managed to interact with the deployed contact by: 

* Setting up a private chain 
* Migrating the contracts to the private chain and then using the compiled _abi_ to call functions from the address of the deployed account

Can push to a new branch for people to play around with it?

![screen shot 2018-01-17 at 13 44 00](https://user-images.githubusercontent.com/18324680/35045692-99b7f060-fb8c-11e7-8b24-d4ca1e9918d4.png)

**Comment by ccdle12** [comment]
Also you can continue to interact with the contract from the truffle develop console:

Just call functions that are publicly available:

* ``` lost.hasEnded() ```
* ``` lot.goal() ```
* ``` lot.rate() ```

Although haven't looked deeply into how to buy the token from the truffle develop console

<img width="457" alt="screen shot 2018-01-17 at 14 50 28" src="https://user-images.githubusercontent.com/18324680/35048815-0fea86fe-fb96-11e7-9030-408eac7ee4a5.png">

**Comment by brtknr** [comment]
Nice! I also managed to buy `LTK` lottery tokens in exchange for ether and see how much I had accumulated so far which I have finally managed. Next stop, get random numbers! I will close this issue as I think I have already had the help I was looking for :) Thanks guys!
